services:
  tts-api:
    build: .
    image: ghcr.io/0xhliu/tts-docker-app:latest
    ports:
      - "8001:8001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AGGREGATOR_URL=${AGGREGATOR_URL:-https://aggregator.walrus-testnet.walrus.space}
    volumes:
      - /storage/output:/app/output
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 